# Generated by Django 5.0.6 on 2024-07-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
