# Generated by Django 5.0.6 on 2024-07-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_date_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_birth",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата рождения"
            ),
        ),
    ]
