# Generated by Django 5.0.6 on 2024-06-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя задачи')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('HIGH', 'High')], default='LOW', max_length=4, verbose_name='Приоритет')),
                ('type', models.CharField(choices=[('SOFT', 'Software'), ('HARD', 'Hardware'), ('OTHER', 'Other')], max_length=5, verbose_name='Тип задачи')),
            ],
        ),
    ]
